sudo: required
dist: trusty

branches:
  only:
    - /.*/

language: c

os: linux

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - deadsnakes
    packages:
      - cmake
      - gcc-7
      - g++-7
      - valgrind
      - cppcheck
      - lcov
      - python3.7

script:
  - pip install --user cpp-coveralls
  - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  - mkdir -p build
  - cd build
  - cmake -DENABLE_COVERAGE=ON -DCMAKE_CXX_COMPILER="g++-7" ..
  - make
  - valgrind --tool=memcheck --leak-check=full --leak-resolution=med ./unit_tests/triangle_matrix_test_static
  - valgrind --tool=memcheck --leak-check=full --leak-resolution=med ./unit_tests/triangle_matrix_test_dynamic
  - cppcheck --enable=all --std=c11 --check-config --suppress=missingIncludeSystem -I ../include ../src -I ../stress_tests/include ../stress_tests/src
  - MATRIX_SIZE=100000
  - MATRIX_FILENAME="random_matrix.txt"
  - ./create_matrix_file ${MATRIX_SIZE} ${MATRIX_FILENAME}
  - ./stress_test_consecutive ${MATRIX_SIZE} ${MATRIX_FILENAME}
  - ./stress_test_parallel ${MATRIX_SIZE} ${MATRIX_FILENAME}
  - cat statistic.txt
  - valgrind --tool=memcheck --leak-check=full --leak-resolution=med ./stress_test_consecutive 100 ${MATRIX_FILENAME} 1
  - valgrind --tool=memcheck --leak-check=full --leak-resolution=med ./stress_test_parallel 100 ${MATRIX_FILENAME} 1

after_success:
  - coveralls --root .. --build-root . -E ".*CMakeFiles.*" -E ".*googletest*" --gcov /usr/bin/gcov --gcov-options '\-lp'